server:
  port: 8080

spring:
  profiles:
    active: dev, aliOssInfo, redisInfo, weChatInfo #必须动态引入包 才能引用
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  servlet:
    multipart:
      max-file-size: 2MB #指定单个文件上传的大小
  #配置Redis集群cluster
  redis:
    # Redis 密码，用于认证连接 默认连接0号数据库  共0~15
    password: ${redis.password}

    # Redis 集群配置
    cluster:
      # 集群节点列表，格式为 host:port
      nodes:
        - ${redis.cluster.nodes[0]}
        - ${redis.cluster.nodes[1]}
        - ${redis.cluster.nodes[2]}
        - ${redis.cluster.nodes[3]}
        - ${redis.cluster.nodes[4]}
        - ${redis.cluster.nodes[5]}

      # 最大重定向次数，用于处理 MOVED/ASK 错误
      max-redirects: 3

    # Lettuce 连接池配置优化 可以不用写
    lettuce:
      cluster:
        refresh:
          adaptive: true #支持集群拓扑动态感应刷新
          period: 2000 #设置2s刷新一次
      pool:
        # 连接池最大活跃连接数
        max-active: 8
        # 连接池最大等待时间（负数表示无限等待）
        max-wait: -1ms
        # 连接池最大空闲连接数
        max-idle: 8
        # 连接池最小空闲连接数
        min-idle: 0

mybatis:
  #mapper配置文件 扫描
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity #给当前路径下的pojo包起别名
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间 设置为30天左右
    admin-ttl: 2600000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #用户端
    user-secret-key: itheima
    user-ttl: 2600000000
    user-token-name: authentication

  alioss: #配置案例oss的配置信息
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

  #微信小程序
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}